#pragma once

#define USE_BOOST_COROUTINE 0

#define USE_UCONTEXT 0

#define USE_FIBER 0

#define USE_BOOST_CONTEXT 1

#define ENABLE_DEBUGGER 0

#define WITH_CARES 0

#define WITH_SAFE_SIGNAL 0

#define LIBGO_SINGLE_THREAD 0
#define BOOST_COROUTINES_NO_DEPRECATION_WARNING
